### ISSUE TITLE
013-list-comprehensions.qmd

### ISSUE THREAD

**Issue by HuwWDay** [Bristol-Training/intermediate-python#1]
The exercise at the bottom of this page in intermediate-python refers to morse.py module that doesn't get made in the course until a later section (the modules bit).

Recommend changing the exercise to something like "change the for loop in encode.py to be made using list comprehension"

**Comment by pauerola** [comment]
fixed, I enclosed the module as a script in the exercise

**Comment by pauerola** [comment]
fixed, I enclosed the module as a script in the exercise

**Comment by HuwWDay** [comment]
[like]  Huw Day reacted to your message:
________________________________
